sudo: false
language: node_js
node_js:
  - "12"
  - "8"
  - "node"

env:
  - TRAVIS_NODE_VERSION="12"
  - TRAVIS_NODE_VERSION="8"

cache:
  directories:
    - bower_components
    - node_modules
    - vendor

install:
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - travis_retry npm install -g npm@latest
  - travis_retry npm install -g bower gulp
  - node -v && npm -v && bower -v && gulp -v
  - npm rebuild
  - travis_retry npm install
  - npm prune

script:
  - npm run build
  - npm run lint
